variables:
  RUN_RENOVATE:
    value: "no"
    options:
      - "yes"
      - "no"
    description: "Set to yes if you want to run renovate"

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_OPEN_MERGE_REQUESTS
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_PROTECTED == "true"
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "webide"
    - if: $RUN_RENOVATE == "yes"

include:
  - local: /.gitlab-ci/gitlab-ci.yml
    rules:
      - if: $RUN_RENOVATE != "yes"
  - project: univention/infrastructure/docker-services
    file:
      - renovatebot/renovate.gitlab-ci.yml
    rules:
      - if: $RUN_RENOVATE == "yes"
